### PR TITLE
Update Dockerfile to 0.4.2

### PR DESCRIPTION
**Pull request by kewegner**
Changed to CLI 0.4.1

### CODE REVIEW

**Review by neeraj-laad — CHANGES_REQUESTED** [review]
lets update this to 0.4.2 now?

**Comment by kewegner** [comment]
Changed to 0.4.2

**Review by neeraj-laad — APPROVED** [review]
LGTM

**Comment by chilanti** [comment]
We are changing the way the CLI version is injected into Dockerfile - closing this.

**Pull request closed without merging**
